spring:
  datasource:
    url: jdbc:mysql://192.168.10.221:3306/paladin?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&useLocalSessionState=true&timezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    #连接池配置
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      auto-commit: true
      idle-timeout: 600000
      pool-name: paladin-pool
      max-lifetime: 86430000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      #      connection-test-query:
      #      minimum-idle:
      #      metric-registry:
      #      health-check-registry:
  mvc:
    throw-exception-if-no-handler-found: true
    log-request-details: true
    static-path-pattern: /statics/**
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: dd/MM/yyyy
      time: HH:mm:ss
  resources:
    add-mappings: false
  redis:
    host: 192.168.10.221
    port: 6379
    timeout: 0
#    password: 111111
  application:
    name: account
  task:
    execution:
      pool:
        core-size: 8
        max-size: 20
    scheduling:
      pool:
        size: 2
  messages:
    basename: static/i18n/messages
  web:
    locale: en_US

#  cloud:
#    loadbalancer:
#      ribbon:
#        enabled: false
#  mail:
#    protocol: smtp
#    host: smtp.xxx.com
#    port: 26
#    username:
#    password:
logging:
  level:
    root: info
    com.paladin.account: info
#pagehelper:
##  自动监测，可以不设置
#  dialect-alias: mysql=com.github.pagehelper.dialect.helper.MySqlDialect
#  auto-dialect: true
#  offset-as-page-num: false
#  row-bounds-with-count: false
#  auto-runtime-dialect: false
#  close-conn: true
#  default-count: true
#  reasonable: true
#  support-methods-arguments: true
#  params: count=countSql
#  page-size-zero: true
mybatis:
  configuration:
    default-statement-timeout: 10000
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
  mapper-locations: mapper/account/*.xml

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-statement-timeout: 600000
    lazy-load-trigger-methods:
  global-config:
    db-config:
      id-type: auto
      update-strategy: not_null
      logic-delete-value: 0
      logic-not-delete-value: 1
#eureka:
#  client:
#    fetch-registry: false
server:
  port: 8090
  tomcat:
    max-http-form-post-size: 2MB
    accesslog:
      buffered: true
      check-exists: true
      directory: logs
      enabled: true
      encoding: utf-8
      condition-if: null
      condition-unless: null
      file-date-format: yyyy-MM-dd
      ipv6-canonical: true
      locale: true
      max-days: 30
      pattern: combined
      prefix: access_log
      rename-on-rotate: true
      request-attributes-enabled: true
      rotate: true
      suffix: .log
  compression:
    enabled: true
    min-response-size: 2KB
  error:
    include-binding-errors: never
    include-exception: true
    include-message: never
    include-stacktrace: never
    path: /error
    whitelabel:
      enabled: true
  http2:
    enabled: true
  max-http-header-size: 8KB



springfox:
  documentation:
    enabled: true
swagger:
  base-package: com.paladin.account
  base-path: /**
  contact:
    email: dyc87112@qq.com
    name: didi
    url: http://blog.didispace.com
  description: Starter for swagger 3.x
  docket:
    administrator:
      contact:
        email: didi@potatomato.club
        name: zhaiyongchao
        url: http://spring4all.com/
      description: Starter for swagger 3.x
      excludePath: /ops/**,/error/**
      globalOperationParameters:
        -   description: some description three override
            modelRef: string
            name: name three
            parameterType: header
      termsOfServiceUrl: https://gitee.com/didispace/spring-boot-starter-swagger
      title: account
      version: 3.0.1.RELEASE
    all:
      title: group-all
    department:
      basePackage: com.paladin.account
      title: group-department
  exclude-path: /error, /ops/**
  global-operation-parameters:
    -   description: user access token
        modelRef: string
        name: access_token
        parameterType: header
        required: true
    -   description: access timestamp
        modelRef: int
        name: timestamp
        parameterType: header
        required: false
  host: localhost:8090
  license: Apache License, Version 2.0
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfServiceUrl: https://github.com/dyc87112/spring-boot-starter-swagger
  title: spring-boot-starter-swagger
  version: 3.0.0.RELEASE